package model.location;

public enum LocationName {
    NORTH_POITIERS,
    BEAULIEU, CITY_CENTER, COURONNERIES,
    GIBAUDERIE, WEST_POITIERS,
    SOUTH_POITIERS, PONT_NEUF, SAINT_ELOI,
    TROIS_CITES, MONTBERNAGE, MILETRIE,
    FINAL_EXIT;
}